name: Generate snake animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main # Altere para "master" se for sua branch principal

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Garante permissões para criar/editar branch

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Gabriel-marques-araujo # Confirme seu nome exato no GitHub
          outputs: dist/snake.svg?palette=github-dark

      - name: Publicar snake.svg na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

